ALTER PUBLICATION supabase_realtime ADD TABLE public.owners;

ALTER TABLE public.owners REPLICA IDENTITY FULL;
ALTER TABLE public.current_auction REPLICA IDENTITY FULL;
ALTER TABLE public.bids REPLICA IDENTITY FULL;
ALTER TABLE public.players REPLICA IDENTITY FULL;
ALTER TABLE public.match_balls REPLICA IDENTITY FULL;
ALTER TABLE public.match_innings REPLICA IDENTITY FULL;